reportes/urls.py
from django.conf.urls import url
from .views import(
    ReporteView,
    GeneracionDepartamentos,
    GeneracionServicios
)

app_name="reportes"
urlpatterns = [
    url(r'^$', GeneracionDepartamentos.as_view(), name="reportes"),
    url(r'^servicios/$', GeneracionServicios.as_view(), name="servicios"),
    url(r'^generacion/$', ReporteView.as_view(), name="generacion"),
]

ventas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^reporte/$',
        view=views.ReporteVentas.as_view(),
        name='reporte'
    ),
]

vive/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.principal,name='principal'),
    url(r'^login/',include('login.urls',namespace='login')),
    url(r'^cita/',include('agenda.urls',namespace='agenda')),
    url(r'^asesor/',include('asesor.urls',namespace='asesor')),
    url(r'^ventas/',include('ventas.urls',namespace='ventas')),
    url(r'^sesion1/',include('sesion1.urls',namespace='sesion1')),
    url(r'^cliente/',include('cliente.urls',namespace='cliente')),
    url(r'^creditos/',include('creditos.urls',namespace='conekta')),
    url(r'^mensajes/',include('mensajes.urls',namespace='mensajes')),
    url(r'^productos/',include('productos.urls',namespace='producto')),
    url(r'^reportes/',include('reportes.urls', namespace='reporte')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reportes/models.py
from django.db import models

ventas/models.py
from django.db import models
from productos.models import Servicio
from login.models import Persona
from django.contrib.auth.models import User
# Create your models here.

class PlazoPagos(models.Model):
    idplazo = models.AutoField(primary_key=True)
    nombrePlazo = models.CharField(max_length=10)

    def __str__(self):
        return(self.nombrePlazo)

class PlanesConcretados(models.Model):
    idPlan = models.AutoField(primary_key=True)
    idAsesor = models.ForeignKey(User)
    idCliente = models.ForeignKey(Persona)
    idServicio = models.ForeignKey(Servicio)
    formaPago = models.ForeignKey(PlazoPagos)
    fechaContratacion = models.DateField()
    numeroPoliza = models.CharField(max_length=10)
    primaNetaAnual = models.FloatField()
    plazoAnos = models.IntegerField()
    valorPlan = models.FloatField()
    observaciones = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return(self.numeroPoliza)

reportes/forms.py
from django import forms
from productos import models as m


    #institucion = forms.ModelChoiceField(queryset = InstitucionFinanciera.objects.all())
    #departamento = forms.ModelChoiceField(queryset=InstitucionFinanciera.objects.all(), required=False)
    #plan = forms.ModelChoiceField(queryset=InstitucionFinanciera.objects.all(), required=False)

ventas/forms.py
from django import forms
INSTITUCIONES = (
    ('smnyl', "Seguros Monterrey"),
    ('allianz', "Allianz"),
)
PLANES = (
    ('plana', "Plan A"),
    ('planb', "Plan B"),
)
class ReporteVentasForm(forms.Form):
    periodoInicial = forms.DateField(label=u'Periodo Inicial', input_formats='%D/%M/%Y', required=True, widget=forms.DateInput(format = '%D/%M/%Y'))
    periodoFinal = forms.DateField(label=u'Periodo Final', input_formats='%D/%M/%Y', required=True, widget=forms.DateInput(format = '%D/%M/%Y'))
    institucion = forms.ChoiceField(choices=INSTITUCIONES)
    plan = forms.ChoiceField(choices=PLANES)

    def cleaned_periodoInicial(self):
        periodoInicial = self.cleaned_data.get("periodoInicial")
        if(len(periodoInicial) < 8 or len(periodoInicial) > 10 ):
            raise forms.ValidationError("El periodo inicial debe tener el formato dd/mm/yyyy")
        else:
            return periodoInicial

    def cleaned_periodoFinal(self):
        periodoFinal = self.cleaned_data.get("periodoFinal")
        if(len(periodoFinal) < 8 or len(periodoFinal) > 10 ):
            raise forms.ValidationError("El periodo final debe tener el formato dd/mm/yyyy")
        else:
            return periodoFinal

    def cleaned_institucion(self):
        institucion = self.cleaned_data.get("institucion")
        if(len(institucion) == 0 or institucion == None):
            raise forms.ValidationError("No se ha seleccionado ninguna institucion financiera")
        else:
            return institucion

    def cleaned_plan(self):
        plan = self.cleaned_data.get("plan")
        if(len(plan) == 0 or plan == None):
            raise forms.ValidationError("No se ha seleccionado ningun plan")
        else:
            return plan

reportes/views.py
import datetime
import json
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from productos.models import InstitucionFinanciera, Departamento, Servicio
from ventas.models import PlanesConcretados
from . import forms as f
from django.db.models import Q


class ReporteView(LoginRequiredMixin, View):

    def desdeInstitucion(self,queryset, datos):
        departamentos = {}
        for institucion in queryset:
            if not datos.get(institucion.idServicio.idDepartamento.idInstitucion.nombre) :
                #print("institucion:{}".format(institucion.idServicio.idDepartamento.idInstitucion.nombre))
                #Ahora se obtienen todos los departamentos pertenecientes a la institucion indicada
                departamentos = self.desdeDepartamento(queryset.filter(idServicio__idDepartamento__idInstitucion__nombre = institucion.idServicio.idDepartamento.idInstitucion.nombre ))
                #Se agrega el diccionario de departamentos con planes al diccionario de las instituciones
                #print("DEPTOS: {}".format(departamentos))
                datos[institucion.idServicio.idDepartamento.idInstitucion.nombre] = departamentos


    def desdeDepartamento(self, queryset):
        planes = {}
        departamentos = {}

        for elem in queryset:
            if not elem.idServicio.idDepartamento.nombre in departamentos:
                #print("depto: {}".format(elem.idServicio.idDepartamento.nombre))
                #Se llama al metodo que devuelve el conjunto de planes para cada departamento
                planes = self.desdePlan(queryset.filter(idServicio__idDepartamento__nombre = elem.idServicio.idDepartamento.nombre))
                #Se contruye el diccionario con el nombre del departamento y sus PLANES
                print("PLANES: {} - {}".format(elem.idServicio.idDepartamento.nombre, type(elem.idServicio.idDepartamento.nombre)))
                print("TYPO: {}".format(type(planes)))
                departamentos[elem.idServicio.idDepartamento.nombre] = planes
                planes = {}

        return departamentos

    def desdePlan(self, queryset):
        planes = {}
        plan = []
        for p in queryset:
            plan.append([p.numeroPoliza, p.formaPago,p.plazoAnos,p.valorPlan])

        print("Nombre Plan: {} - {}".format(p.idServicio.nombrePlan, type(p.idServicio.nombrePlan)))
        planes[p.idServicio.nombrePlan] = plan

        return planes

    def post(self, request, *args, **kwargs):
        #form = ReporteForm(request.POST)
        #print("FORM: {}".format(form))
        #se valida que el id de la Institucionfinanciera se encuentre en sessions
        #template = get_template('reportes/reporte.html')
        template = 'reportes/reporte.html'
        #pInicial = self.request.POST.get('periodoInicial')
        #pFinal = self.request.POST.get('periodoFinal')
        pInicial = self.request.POST.get('start')
        pFinal = self.request.POST.get('end')
        #print("\n\n*******Fechas: {}".format(Fechas))
        print("Periodos: {} - {}".format(pInicial, pFinal))
        datos = {}

        if self.request.session.has_key('institucion'):
            inst = self.request.session['institucion']
            if(inst == "0"):
                #se Obtiene el query set que trae todos los planes de todas las instituciones financieras pertenecientes al asesor indicado, en la fecha solicitada
                queryset = PlanesConcretados.objects.filter(Q(idAsesor=request.user.id), Q(fechaContratacion__range=[pInicial,pFinal]))
                self.desdeInstitucion(queryset, datos)
                # se define el nivel de que el usuario selecciono para ver como se organizan las graficas
                nivel = "Institucion Todos"
            else:
                if(self.request.session.has_key('departamento')):
                    deptos = self.request.session['departamento']
                    if(deptos == "0"):
                        queryset = PlanesConcretados.objects.filter(Q(idAsesor=request.user.id), Q(fechaContratacion__range=[pInicial,pFinal])).filter(idServicio__idDepartamento__idInstitucion = inst)
                        #print("NOMBRE INST: {}".format(queryset[0].idServicio.idDepartamento.idInstitucion.nombre))
                        #datos[queryset[0].idServicio.idDepartamento.idInstitucion.nombre] = self.desdeDepartamento(queryset)
                        self.desdeInstitucion(queryset,datos)
                        #print("Datos: {}".format(datos))
                        # se define el nivel de que el usuario selecciono para ver como se organizan las graficas
                        nivel = "Departamentos Todos"

                    else:
                        plan = self.request.POST.get('plan')
                        #print("deptos: {}".format(deptos))
                        if(plan == "0"):
                            #pk_depto = departamentos.objects.get("")
                            queryset = PlanesConcretados.objects.filter(Q(idAsesor=request.user.id), Q(fechaContratacion__range=[pInicial,pFinal])).filter(idServicio__idDepartamento__idDepartamento = deptos).filter(idServicio__idDepartamento__idInstitucion = inst)
                            #queryset1 = PlanesConcretados.objects.filter(idAsesor=request.user.id, idServicio__idDepartamento__idInstitucion = inst, idServicio__idDepartamento__idDepartamento = deptos).values()
                            #print("QUERySET!: {}".format(qset))
                            #for x in qset:
                            #    print("NOMBRE INST: {}".format(x.idServicio.idDepartamento.idInstitucion.nombre))
                            #    print("NOMBRE DEPTO: {}".format(x.idServicio.idDepartamento.nombre))
                                #datos[x.idServicio.idDepartamento.idInstitucion.nombre] = {x.idServicio.idDepartamento.nombre : self.desdePlan(qset)}
                            self.desdeInstitucion(queryset,datos)
                            print("Datos X: {}".format(datos))
                            # se define el nivel de que el usuario selecciono para ver como se organizan las graficas
                            nivel = "Planes Todos"
                        else:
                            queryset = PlanesConcretados.objects.filter(Q(idAsesor=request.user.id), Q(fechaContratacion__range=[pInicial,pFinal])).filter(idServicio__idDepartamento__idInstitucion = inst).filter(idServicio__idDepartamento__idDepartamento = deptos).filter(idServicio = plan)
                            #for p in queryset:
                                #datos[p.idServicio.idDepartamento.idInstitucion.nombre] = {p.idServicio.idDepartamento.nombre : self.desdePlan(queryset)}
                            self.desdeInstitucion(queryset, datos)
                            print("Datos Y: {}".format(datos))
                            # se define el nivel de que el usuario selecciono para ver como se organizan las graficas
                            nivel = "Plan Especifico"
                #datos = {}

        else:
            print("No se encontro el valor de la institucion")

        print("\n\n______________________")
        print("DATOS: {}\n\n".format(datos))
        for inst in datos.keys():
            print(inst)
            deptos = datos[inst]
            for d in deptos.keys():
                print("\t{}\n".format(d))
                planes = deptos[d]
                for keyArr, valueArr in planes.items():
                    print("---\t\t  {}\n".format(keyArr))
                    for x in valueArr:
                        for y in x:
                            print("\t\t\tdatos: {}".format(y))
        print("\n\n______________________")

        context = {
            "datos":datos,
            "nivel": nivel,
            "asesor": request.user,
        }
        return render(request,template, context)

        '''#la redenderizacion se hace en un html
        html = template.render(context)
        #La renderizacion de hace a un render_to_pdf
        pdf = render_to_pdf('reportes/reporte.html', context)
        print("PDF: {}".format(pdf))
        if pdf:
            response = HttpResponse(pdf, content_type = 'application/pdf')
            #print("USER: {}".format(request.user))
            filename = "Reporte_%s.pdf" %(request.user)
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse("nor found")'''


class GeneracionServicios(View):

    def post(self, request, *args, **kwargs):
        plan = {}
        depto = self.request.POST.get('departamento')
        #print("DEPTO: {}".format(depto))

        #se sube a la sesion el id del departamento
        request.session['departamento'] = depto

        if(request.is_ajax()):
            if(depto == "0"):
                print("Todos")
                x = ["Todos"]
                plan["planes"] = x
                return JsonResponse(plan, safe=False)
            else:
                print("Departamento especifico")
                plan["planes"] = list(Servicio.objects.filter(idDepartamento__pk=depto).values_list('nombrePlan', 'idServicio'))
                plan["planes"].insert(0,("----------","-1"))
                plan["planes"].insert(1,("Todos","0"))
                #print("PLANES: {}".format(plan))
                return JsonResponse(plan, safe=False)

    def get(self, request, *args, **kwargs):
        template = "reportes/ventas.html"
        context = {}
        '''departamento = f.departamentoForm()
        print("Departamento***: {}".format(departamento))
        context = {

ventas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from io import BytesIO
from reportlab.pdfgen import canvas
from django.views.generic import View

from .forms import ReporteVentasForm

class ReporteVentas(View):

    def creaReporte_view(request):
        print(request.POST)
        form = ReporteVentasForm(request.POST or None)
        if(form.is_valid()):
            print(form)
            data = form.cleaned_data
            periodoInicial = data.get("periodoInicial")
            periodoFinal = data.get("periodoFinal")
            institucion = data.get("institucion")
            plan = data.get("plan")
        template = "ventas/ventas.html"
        context = {
            "form" : form,
        }
        return render(request, template, context)

    def cabecera(self,pdf):
        # Utilizamos el archivo logo_django.png que esta guardado en la carpeta media/imagenes
        archivo_imagen = (settings.MEDIA_ROOT+'/images/vive/a.png')
        # Definimos el tamano de la imagen a cargar y las coordenadas correspondientes
        pdf.drawImage(archivo_imagen, 40, 750, 120, 70, preserveAspectRatio=True)

        # Establecemos el tamanio de letra en 16 y el tipo de letra Helvetica
        pdf.setFont("Helvetica", 18)
        # Dibujamos una cadena en la ubicacion X,Y especificada
        pdf.drawString(230, 790, u"VIVE TU FUTURO")
        pdf.setFont("Helvetica", 14)
        pdf.drawString(200, 770, u"REPORTE DE VENTAS")

    def get(self, request, *args, **kwargs):
        # Indicamos el tipo de contenido a devolver, en este caso un pdf
        response = HttpResponse(content_type='application/pdf')
        # La clase io.BytesIO permite tratar un array de bytes como un fichero binario, se utiliza como almacenamiento temporal
        buffer = BytesIO()
        # Canvas nos permite hacer el reporte con coordenadas X y Y
        pdf = canvas.Canvas(buffer)
        # Llamo al metodo cabecera donde estan definidos los datos que aparecen en la cabecera del reporte.
        self.cabecera(pdf)
        # Con show page hacemos un corte de pagina para pasar a la siguiente
        pdf.showPage()
        pdf.save()
        pdf = buffer.getvalue()
        buffer.close()
        response.write(pdf)
        return response

templates/reportes/reporte.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title %}Reporte{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" %}">
{% endblock %}
{% block content %}
  <div class="content animate-panel">
      <div class="row">
          <div class="col-lg-12">
              <div class="hpanel hgreen">
                <div class="panel-heading mayusculas">
                    Reporte de Ventas para {{asesor}}
                </div>
                <div class="panel-body">

                    <div class="col-md-8">
                        <canvas id="sharpLineOptions" height="140"></canvas>
                    </div>

                </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

{% block javascripts %}
    <script src="{% static "vendor/datatables/media/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js" %}"></script>

    <script>

    $(function () {
         nivel = "{{ nivel }}"
         graficas = "{{ datos | safe }}";
         console.log("nivel: " + nivel)
         console.log("graficas: " + graficas)

         //Se hace realiza la extraccion de los datos de cada compañia(nombre, # de polizas, y total de Prima anualizada)
        resultados = ExtraccionDatos(graficas, nivel)
        console.log("resultados: "+ resultados)
        //GraficaBarras(instituciones, polizas, primaAnual);

    });

    //funcion que realiza la extraccion de datos para su graficacion
    function ExtraccionDatos(graficas, nivel){
      resultados = {}
      instituciones = []
      departamentos = []
      planes = []
      polizas = []
      primaAnual = []
      sumPolizas = 0;
      sumPrimaAnual = 0;

      console.log("Estamos aqui")
      console.log(graficas)

      {% for keyInst,valueInst in graficas.items%}
        console.log("----- ");
        instituciones.push("{{keyInst | safe }}")
        {% for keyDepto,valueDepto in valueInst.items %}
          console.log("==== " + valueDepto);
          departamentos.push("{{keyDepto | safe}}")
          {% for keyPlan, valuePlan in valueDepto.items%}
            console.log("VP: " + "{{valuePlan | safe}}")


            //planes.push("{{valuePlan | safe}}")
            /*{% for valueDatos in valuePlan %}

              planes.push("{{valueDatos | safe}}")
              if("polizas" == "{{keyDatos | safe}}"){
                sumPolizas = sumPolizas + parseInt("{{valueDatos | safe}}")
              }
              else if ("primaAnual" == "{{keyDatos | safe}}") {
                sumPrimaAnual = sumPrimaAnual + parseInt("{{valueDatos | safe}}")
              }
            {%endfor%}*/
          {% endfor %}
        {%endfor%}
        polizas.push(sumPolizas);
        primaAnual.push(sumPrimaAnual);
        sumPolizas = 0;
        sumPrimaAnual = 0;
      {%endfor%}

      console.log("I: " + instituciones)
      console.log("D: " + departamentos)
      console.log("P: " + planes)
      console.log("Polizas: " + polizas)
      console.log("PrimaAnual: " + primaAnual)

      if(nivel == "Institucion Todos"){
        resultados["label"] = instituciones
      }
      else if (nivel == "Departamentos Todos") {
        resultados["label"] = departamentos
      }
      else if (nivel == "Planes Todos" || nivel == "Plan Especifico") {
        resultados["label"] = planes
      }
      resultados["polizas"] = sumPolizas
      resultados["primaAnual"] = sumPrimaAnual
      return resultados
    }

    //Funcion que contiene la grafica (Barras)
    function GraficaBarras(instituciones, polizas, primaAnual){
      /**
       * Options for Bar chart
       */
      var barOptions = {
          scaleBeginAtZero : true,
          scaleShowGridLines : true,
          scaleGridLineColor : "rgba(0,0,0,.05)",
          scaleGridLineWidth : 1,
          barShowStroke : true,
          barStrokeWidth : 1,
          barValueSpacing : 5,
          barDatasetSpacing : 1,
          responsive:true
      };

      /**
       * Data for Bar chart
       */
      var barData = {
          labels: instituciones,
          datasets: [
              {
                  label: "polizas",
                  fillColor: "rgba(220,220,220,0.5)",
                  strokeColor: "rgba(220,220,220,0.8)",
                  highlightFill: "rgba(220,220,220,0.75)",
                  highlightStroke: "rgba(220,220,220,1)",
                  data: polizas
              },
              {
                  label: "Prima Anualizada",
                  fillColor: "rgba(98,203,49,0.5)",
                  strokeColor: "rgba(98,203,49,0.8)",
                  highlightFill: "rgba(98,203,49,0.75)",
                  highlightStroke: "rgba(98,203,49,1)",
                  data: primaAnual
              }
          ]
      };
      var ctx = document.getElementById("barOptions").getContext("2d");
      var myNewChart = new Chart(ctx).Bar(barData, barOptions);
    }

  </script>
{% endblock %}

templates/reportes/ventas.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title %}Ventas{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" %}">
  <link rel="stylesheet" href="{% static "vendor/bootstrap-datepicker-master/dist/css/bootstrap-datepicker3.min.css" %}">
{% endblock %}
{% block content %}
  <div class="content animate-panel">
      <div class="row">
          <div class="col-lg-12">
              <div class="hpanel hgreen">
                <div class="panel-heading mayusculas">
                    Ventas
                </div>
                <div class="panel-body">

                  <div class='text-center'>
                      <h1>{{title}}</h1>
                      <div class="container">
                        <div class="row">
                          <div class="col">
                            <p>{{ content }}</p>
                          </div>
                        </div>
                      </div>
                  </div>

                 <div class="col-sm-6 col-12">
                    <!--<form method="POST">
                      {% csrf_token %}
                      {{ form.as_p}}
                      <button type="submit" class="btn btn-default">Submit</button>
                    </form>-->

                    <form action="generacion/" method="POST">
                      <div class="form-group">
                        <h3>Selecciona las opciones, para generar el reporte</h3>
                        {% csrf_token %}
                        <label class="control-label">Selecciona Fecha </label>
                        <div class="input-daterange input-group" id="datepicker">
                            <span class="input-group-addon"> De </span>
                            <input type="text" class="input-sm form-control" name="start" />
                            <span class="input-group-addon"> a </span>
                            <input type="text" class="input-sm form-control" name="end" />
                        </div>

                        <label class="control-label">Selecciona la Institucion Financiera</label>

                        <select class="form-control m-b" id="id_institucion" name="id_institucion">
                          {% for item in institucion%}
                            <option value="{{item.1}}" > {{item.0}} </option>
                          {% endfor %}
                        </select>

                        <select class="form-control m-b" id="id_departamento" name="id_departamento">
                        </select>

                        <select class="form-control m-b" id="id_plan" name="id_plan">
                        </select>

                        <button type="submit" class="btn btn-success">Ir</button>
                      </div>
                    </form>
                  </div>

                </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

{% block javascripts %}
    <script src="{% static "vendor/datatables/media/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap-datepicker-master/dist/js/bootstrap-datepicker.min.js" %}" charset="UTF-8"></script>
    <script src="{% static "vendor/bootstrap-datepicker-master/dist/locales/bootstrap-datepicker.es.min.js" %}" charset="UTF-8"></script>

    <script>

    $(function () {
          //Calendario.
          $('#datepicker').datepicker({
              language: 'es',
              locale: {
                format: 'YYYY-MM-DD'
              },
          });

          $("#datepicker").on("changeDate", function(event) {
              $("#my_hidden_input").val(
                      $("#datepicker").datepicker('getFormattedDate')
              )
          });

          {% block jquery %}

              //Se ocultan los select para que paso a paso se vayan seleccionando las opciones que el usuario quiera
              $("label[for=id_departamento], #id_departamento").hide();
              $("label[for=id_plan], #id_plan").hide();

              //Se agrega una opcion adicional al primer select (InstitucionesFinancieras) con la opcion de Todas
              $("#id_institucion").append('<option value="0">Todos</option>');

              //Cuando el choice field de institucion cambia
              $("#id_institucion").change(function(){
                  var inst = $("#id_institucion").val()
                  console.log(inst)
                  var request = $.ajax({
                    method: "POST",
                    url: "",
                    data:{
                      institucion: inst,
                      csrfmiddlewaretoken: "{{ csrf_token }}",
                    }
                  })
                  request.done(function(depto){
                    $("#id_departamento").empty()
                    if(depto.length != 0){
                      if(depto.deptos == "Todos"){
                        console.log("Deptos: " + depto.deptos)
                        $("label[for=id_departamento], #id_departamento").hide();
                        $("label[for=id_plan], #id_plan").hide();
                        $("#id_departamento").empty()
                        $("#id_plan").empty()
                      }
                      else{
                        if(inst != ''){
                          console.log("Deptos: " + depto.deptos)
                          $("label[for=id_departamento], #id_departamento").show();
                          $.each(depto.deptos, function(index, value){
                              $('#id_departamento').append('<option value="'+ value[1]+'">'+value[0]+'</option>')
                          });
                        }
                        else{
                          console.log("Ocultando el select de Departamentos y planes")
                          $("label[for=id_departamento], #id_departamento").hide();
                          $("label[for=id_plan], #id_plan").hide();
                        }
                      }
                    }
                  })
                  request.fail(function(jqXHR, textStatus){
                    if(jqXHR.status == 404){
                      alert("Page not found")
                    }
                    else{
                      alert("There was an error with your request. Please try again")
                    }
                  })
              });

              //cuando el choice field de departamento cambia
              $("#id_departamento").change(function(){
                var depto = $("#id_departamento").val()
                var request = $.ajax({
                  method: "POST",
                  url: "servicios/",
                  data: {
                    departamento: depto,
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                  }
                });
                request.done(function(plan){
                  $("#id_plan").empty()
                  if(plan.length !=0 && plan.planes != "----------,Todos" ){
                    if(depto == 0){
                      console.log("Planes: " + plan.planes)
                      $("label[for=id_plan], #id_plan").hide();
                    }
                    else{
                      if(depto != ''){
                        console.log("Planes: " + plan.planes)
                        $("label[for=id_plan], #id_plan").show();
                        $.each(plan.planes, function(index, value){
                            $('#id_plan').append('<option value="'+ value[1]+'">'+value[0]+'</option>')
                        });
                      }
                    }
                  }
                  else{
                    console.log("Ocultando el select de planes")
                    $("label[for=id_plan], #id_plan").hide();
                  }
                })
                request.fail(function(){
                  if(jqXHR.status == 404){
                    alert("Page not found")
                  }
                  else{
                    alert("There was an error with your request. Please try again")
                  }
                })
              });

          {% endblock jquery%}
    });

  </script>
{% endblock %}