agenda/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
urlpatterns = [
    url(
        regex=r'^contactos',
        view=views.contactos,
        name='contactos'
    ),
    url(
        regex=r'^$',
        view=views.calendario,
        name='calendario'
    ),
    url(
        regex=r'^agendar/(?P<idAsesorCliente>\d+)$',
        view=views.agenda,
        name='agendar'
    ),
    url(
        regex=r'^editar/(?P<idCita>\d+)$',
        view=views.editar,
        name='editar'
    ),
    url(
        regex=r'^eliminar/(?P<idCita>\d+)$',
        view=views.eliminar,
        name='eliminar'
    ),
    url(
        regex=r'^hoy/',
        view=views.hoy,
        name='hoy'
    ),
    url(
        regex=r'^historial/',
        view=views.historial,
        name='historial'
    ),
]

login/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.conf.urls import handler404


urlpatterns = [
    url(r'^logout/$',auth_views.logout,{'template_name':'hola.html'},'logout'),
    url(
        regex=r'^$',
        view=views.login,
        name='login'
    ),
    url(
        regex=r'^hola/$',
        view=views.hola,
        name='hola'
    ),

]

vive/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.principal,name='principal'),
    url(r'^login/',include('login.urls',namespace='login')),
    url(r'^cita/',include('agenda.urls',namespace='agenda')),
    url(r'^asesor/',include('asesor.urls',namespace='asesor')),
    url(r'^ventas/',include('ventas.urls',namespace='ventas')),
    url(r'^sesion1/',include('sesion1.urls',namespace='sesion1')),
    url(r'^cliente/',include('cliente.urls',namespace='cliente')),
    url(r'^creditos/',include('creditos.urls',namespace='conekta')),
    url(r'^mensajes/',include('mensajes.urls',namespace='mensajes')),
    url(r'^productos/',include('productos.urls',namespace='producto')),
    url(r'^reportes/',include('reportes.urls', namespace='reporte')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agenda/models.py
from django.db import models
from login.models import Persona
from cliente.models import AsesorCliente
# Create your models here.

class CatEstatuscita(models.Model):
    idEstatus = models.BigIntegerField(primary_key=True)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return (self.nombre)

class CatTipocita(models.Model):
    idTipoCita = models.BigIntegerField(primary_key=True)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return (self.nombre)

class Cita(models.Model):
    idCita = models.AutoField(primary_key=True)
    idAsesorCliente = models.ForeignKey(AsesorCliente)
    idTipoCita = models.ForeignKey(CatTipocita)
    idEstatus = models.ForeignKey(CatEstatuscita)
    fecha = models.DateTimeField()
    direccionCita = models.CharField(max_length=200, blank=True, null=True)
    descripcion = models.CharField(max_length=500, blank=True, null=True)
    link = models.CharField(max_length=300,blank=True, null=True)
    password = models.CharField(max_length=10,blank=True, null=True)

agenda/forms.py
from django import forms
from . import models as m
from django.forms.extras.widgets import SelectDateWidget

class agendaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(agendaForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {
                'class': 'form-control'
            }
            self.fields['idTipoCita'].label = "Tipo de cita"
            self.fields['idEstatus'].label = "Estado de la cita"
            self.fields['direccionCita'].label = "Direcion de la cita (en caso de ser presencial)"
            self.fields['link'].label = "Link de la cita (en caso de ser por videollamada)"
            self.fields['password'].label = "Password"
    class Meta:
        model = m.Cita
        fields = (
            "idTipoCita",
            "idEstatus",
            "fecha",
            "direccionCita",
            "link",
            "password",
            "descripcion"
        )
        widgets = {
            'fecha': SelectDateWidget,
        }

agenda/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from datetime import datetime,timedelta
from . import forms as f
import cliente.models as m
from . import models as mCita
from cliente import models as mCliente
# Create your views here.

@login_required(redirect_field_name='login:login')
def agenda(request,idAsesorCliente):
    if request.user.persona.idRol.idRole == 2 or request.user.persona.idRol.idRole == 3:
        if request.method == "POST":
            tipoCita = request.POST.get("idTipoCita",None)
            estadoCita = request.POST.get("idEstatus",None)
            mes = request.POST.get("fecha_month",None)
            dia = request.POST.get("fecha_day",None)
            ano = request.POST.get("fecha_year",None)
            hora = request.POST.get("hora",None)
            fecha = ano+"-"+mes+"-"+dia+" "+hora
            fecha = datetime.strptime(fecha,"%Y-%m-%d %H:%M")
            direccion = request.POST.get("direccionCita",None)
            descripcion = request.POST.get("descripcion",None)
            estado = mCita.CatEstatuscita.objects.get(idEstatus=estadoCita)
            tipoCita = mCita.CatTipocita.objects.get(idTipoCita=tipoCita)
            asesorCliente = mCliente.AsesorCliente.objects.get(idAsesorCliente=idAsesorCliente)
            cita = mCita.Cita(
                idAsesorCliente = asesorCliente,
                idTipoCita = tipoCita,
                idEstatus = estado,
                direccionCita  = direccion,
                descripcion = descripcion,
                fecha = fecha,
            )
            mCliente.AsesorCliente.objects.filter(idAsesorCliente=idAsesorCliente).update(
                fecha = fecha,
                estatusCita = estadoCita,
            )
            cita.save()
            return redirect('agenda:contactos')
        else:
            cita = f.agendaForm()
            context = {
                "cita":cita,
            }
            return render(request,"agenda/agenda.html",context)
    else:
        return render(request,'error/404.html')

@login_required(redirect_field_name='login:login')
def contactos(request):
    if request.user.persona.idRol.idRole == 2 or request.user.persona.idRol.idRole == 3:
        asesorClientes = m.AsesorCliente.objects.filter(idAsesor=request.user.id)
        cita = []
        sin_agendar = []
        dia = datetime.today().strftime("%Y-%m-%d")
        for i in range(0,len(asesorClientes)):
            try:
                citas = mCita.Cita.objects.get(idAsesorCliente=asesorClientes[i],fecha=asesorClientes[i].fecha)
                print(asesorClientes[i].estatusCita)
                if asesorClientes[i].fecha.strftime("%Y-%m-%d") >= dia and asesorClientes[i].estatusCita != "10":
                    cita.append(citas)
                else:
                    sin_agendar.append(asesorClientes[i])
            except:
                sin_agendar.append(asesorClientes[i])
        if len(sin_agendar) == 0:
            bien = 1
        else:
            bien = 0
        context = {
            "clientes":asesorClientes,
            "sin_cita":sin_agendar,
            "citas":cita,
            "bien":bien,
        }
        return render(request,"agenda/contactos.html",context)
    else:
        return render(request,'error/404.html')

@login_required(redirect_field_name='login:login')
def editar(request,idCita):
    if request.user.persona.idRol.idRole == 2 or request.user.persona.idRol.idRole == 3:
        editar = mCita.Cita.objects.get(idCita=idCita)
        if request.method == "POST":
            editar = mCita.Cita.objects.filter(idCita=idCita)
            tipoCita = request.POST.get("idTipoCita",None)
            estadoCita = request.POST.get("idEstatus",None)
            mes = request.POST.get("fecha_month",None)
            dia = request.POST.get("fecha_day",None)
            ano = request.POST.get("fecha_year",None)
            hora = request.POST.get("hora",None)
            fecha = ano+"-"+mes+"-"+dia+" "+hora
            fecha = datetime.strptime(fecha,"%Y-%m-%d %H:%M")
            direccion = request.POST.get("direccionCita",None)
            descripcion = request.POST.get("descripcion",None)
            estado = mCita.CatEstatuscita.objects.get(idEstatus=estadoCita)
            tipoCita = mCita.CatTipocita.objects.get(idTipoCita=tipoCita)
            editar.update(
                idTipoCita = tipoCita,
                idEstatus = estado,
                direccionCita  = direccion,
                descripcion = descripcion,
                fecha = fecha,
            )
            editar = mCita.Cita.objects.get(idCita=idCita)
            mCliente.AsesorCliente.objects.filter(idAsesorCliente=editar.idAsesorCliente.idAsesorCliente).update(
                fecha = fecha,
                estatusCita = estadoCita,
            )
            return redirect('agenda:contactos')
        else:
            cita = f.agendaForm(instance=editar)
            context = {
                "cita":cita,
            }
            return render(request,"agenda/agenda.html",context)

    else:
        return render(request,'error/404.html')

@login_required(redirect_field_name='login:login')
def eliminar(request,idCita):
    if request.user.persona.idRol.idRole == 2 or request.user.persona.idRol.idRole == 3:
        eliminar = mCita.Cita.objects.filter(idCita=idCita)
        estado = mCita.CatEstatuscita.objects.get(idEstatus=10)
        eliminar.update(
            idEstatus = estado,
        )
        eliminar = mCita.Cita.objects.get(idCita=idCita)
        eliminar = mCliente.AsesorCliente.objects.filter(idAsesorCliente=eliminar.idAsesorCliente.idAsesorCliente)
        eliminar.update(
            estatusCita = "10",
        )
        return redirect('agenda:contactos')
    else:
        return render(request,'error/404.html')

@login_required(redirect_field_name='login:login')
def hoy(request):
    if request.user.persona.idRol.idRole == 2 or request.user.persona.idRol.idRole == 3:
        asesorClientes = mCliente.AsesorCliente.objects.filter(idAsesor=request.user.id)
        hoy1 = []
        hoy2 = []
        iterar = 0
        dia = datetime.today().strftime("%Y-%m-%d")
        for i in asesorClientes:
            print(i.fecha, i.idAsesorCliente)
            try:
                if i.fecha.strftime("%Y-%m-%d") == dia and i.estatusCita != "10":
                    hoy1.append(mCita.Cita.objects.get(idAsesorCliente=i,fecha=i.fecha))
            except:
                pass
        context = {
            "hoy1":hoy1,
        }
        return render(request,"agenda/hoy.html",context)
    else:
        return render(request,'error/404.html')

@login_required(redirect_field_name='login:login')
def historial(request):
    if request.user.persona.idRol.idRole == 2 or request.user.persona.idRol.idRole == 3:
        asesorClientes = mCliente.AsesorCliente.objects.filter(idAsesor=request.user.id)
        historial1 = []
        historial2 = []
        iterar = 0
        for i in asesorClientes:
            try:
                if iterar%2 == 0:
                    historial1.append(mCita.Cita.objects.filter(idAsesorCliente=i))
                    print(historial1)
                else:
                    historial2.append(mCita.Cita.objects.filter(idAsesorCliente=i))
            except:
                pass
            iterar = iterar + 1

        context = {
            "historial1":historial1,
            "historial2":historial2,
        }
        return render(request,"agenda/historial.html",context)
    else:
        return render(request,'error/404.html')

@login_required(redirect_field_name='login:login')
def calendario(request):
    if request.user.persona.idRol.idRole == 2 or request.user.persona.idRol.idRole == 3:
        asesorClientes = m.AsesorCliente.objects.filter(idAsesor=request.user.id)
        cita = []
        hora = []
        minutos = []
        print(len(asesorClientes))
        for i in range(0,len(asesorClientes)):
            try:
                cita.append(mCita.Cita.objects.filter(idAsesorCliente=asesorClientes[i]))
                hora.append(cita[i].hour)
                minutos.append(cita[i].minute)
            except:
                pass
        print(cita)
        context = {
            "cita":cita,
            "hora":hora,
            "minutos":minutos,
        }
        return render(request,"agenda/calendario.html",context)
    else:
        return render(request,'error/404.html')

templates/agenda/agenda.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title %}Agenda{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static "styles/vive.css" %}"/>
{% endblock %}
{% block content %}
<div class="content animate-panel">
<form method="POST">
  {% csrf_token %}
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel hgreen">
                <div class="panel-heading mayusculas">
                      <h3>Agendar Cita</h3>
                </div>
                <div class="panel-body">
                  {{cita.as_p}}
                  <label>Hora: </label>
                  <input type="time" name="hora" required>
                </div>
            </div>
        </div>
    </div>
    <div class="text-right m-t-xs">
        <button class ="btn btn-success btn-m" type="submit">Haz la cita!</button>
        <a href="{% url 'agenda:contactos' %}" class="btn btn-info btn-m">
            <span class="bold">Regresar</span>
            <i class="fa fa-angle-right"></i>
        </a>
    </div>
  </form>
</div>
<!-- Vendor scripts -->
{% endblock %}

templates/agenda/calendario.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{%block title%}Tus Citas{%endblock%}

<!-- CSS individuales -->
{% block css %}
    <link rel="stylesheet" href="{% static "vendor/fullcalendar/dist/fullcalendar.print.css"%}" media='print'>
    <link rel="stylesheet" href="{% static "vendor/fullcalendar/dist/fullcalendar.min.css" %}">
{% endblock %}

{% block content %}
  <div class="content">
    <div class="row">
      <div class="col-lg-12">
        <div class="hpanel">
          <div class="panel-body">
            <div class="text-center m-b-md" id="wizardControl">
            </div>
            <div class="tab-content">
              <div class="p-m tab-pane active">
                <div class="row">
                  <div class="col-lg-2 text-center">
                    <i class="pe-7s-date fa-5x text-muted"></i>
                    <p class="middle m-t-md">
                      <strong>Tus citas. <br>Organizate a tus tiempos </strong>
                    </p>
                    <p class="middle m-t-md">
                      <a href="{% url 'agenda:contactos' %}" class="btn btn-success">
                        Agrega citas <span class="icono-der fa fa-plus"></span>
                      </a>
                    </p>
                    <p class="middle m-t-md">
                      <a href="{% url 'agenda:historial' %}" class="btn btn-info">
                        Ver historial <span class="icono-der pe-7s-clock"></span>
                      </a>
                    </p>
                  </div>
                  <div class="col-lg-10">
                    <div id="calendar"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block javascripts %}
  <script src="{% static "vendor/moment/min/moment.min.js" %}"></script>
  <script src="{% static "vendor/fullcalendar/dist/fullcalendar.min.js" %}"></script>
  <script src="{% static "vendor/fullcalendar/dist/lang-all.js" %}"></script>

  <script>

  function activar(){
    $(this).click();
    console.log(""+$(this));
      $('#calendar').fullCalendar('render');
    }

    $(function(){

        /* initialize the calendar
         -----------------------------------------------------------------*/
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();

        $('#calendar').fullCalendar({
          //lang: 'es',
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            editable: false, //true
            droppable: false, //true, this allows things to be dropped onto the calendar
            drop: function() {
                // is the "remove after drop" checkbox checked?
                if ($('#drop-remove').is(':checked')) {
                    // if so, remove the element from the "Draggable Events" list
                    $(this).remove();
                }
            },
            events: [
                  {% for k in cita %}
                    {% for k1 in k %}
                    {
                      title: "{{k1.idAsesorCliente.idCliente.user.first_name}} {{k1.idAsesorCliente.idCliente.user.last_name}}",
                      start: Date.parse("{{k1.fecha.isoformat}}"),
                      allDay: false
                    },
                    {% endfor %}
                  {% endfor %}
            ],
        });
      //Funcion da estilo a botones
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            $('a[data-toggle="tab"]').removeClass('btn-success');
            $('a[data-toggle="tab"]').addClass('btn-default');
            $(this).removeClass('btn-default');
            $(this).addClass('btn-info');
        })

        /* initialize the external events
         -----------------------------------------------------------------*/
        $('#external-events div.external-event').each(function() {

            // store data so the calendar knows to render an event upon drop
            $(this).data('event', {
                title: $.trim($(this).text()), // use the element's text as the event title
                stick: true // maintain when user navigates (see docs on the renderEvent method)
            });

            // make the event draggable using jQuery UI
            $(this).draggable({
                zIndex: 1111999,
                revert: true,      // will cause the event to go back to its
                revertDuration: 0  //  original position after the drag
            });

        });

        activar();
    });
  </script>
{% endblock %}

templates/agenda/contactos.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title%} Mis Clientes {% endblock %}
{% block content %}
<div class="normalheader transition animated fadeIn">
  <div class="hpanel">
      <div class="panel-body">
          <a class="small-header-action" href="">
              <div class="clip-header">
                  <i class="fa fa-arrow-up"></i>
              </div>
          </a>
          <h2 class="font-light m-b-xs">
              {% if bien == 0 %}
                  Esfuerzate un poco mas, tu puedes!
              {% else %}
                Es impresionante! Todos tus clientes tienen cita. Felicidades sigue asi. :)
              {% endif %}
          </h2>
      </div>
  </div>
</div>
  <div class="content animate-panel">
    <div class="row">
      <div class="col-lg-12">
        <div class="hpanel hgreen">
          <div class="panel-heading mayusculas">
            Citas
          </div>
          <div class="panel-body">
            <table id="clientesTable" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Tipo de Cita</th>
                    <th>Estado</th>
                    <th>Direccion</th>
                    <th>Fecha y Hora</th>
                    <th>Descripcion</th>
                    <th>Opciones</th>
                </tr>
              </thead>
              <tbody>
                {% for i in citas %}
                  <tr>
                      <td>{{i.idAsesorCliente.idCliente.user.first_name}} {{i.idAsesorCliente.idCliente.user.last_name}}</td>
                      <td>{{i.idTipoCita.nombre}}</td>
                      <td>{{i.idEstatus.nombre}}</td>
                      <td>{{i.direccionCita}}</td>
                      <td>{{i.fecha}}</td>
                      <td>{{i.descripcion}}</td>
                      <td>
                        <a href="{% url 'agenda:editar' i.idCita %}" class="white a_white">
                          <button class="btn btn-warning btn-xs" type="button">
                              <i class="fa fa-pencil"></i>
                          </button>
                        </a>

                        <button class="btn btn-danger btn-xs" type="button" data-toggle="modal" data-target="#{{i.idCita}}">
                            <i class="fa fa-times"></i>
                        </button>
                        <div class="modal fade" id="{{i.idCita}}" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="color-line"></div>
                                        <div class="modal-header text-center">
                                            <h4 class="modal-title">Eliminar Cita</h4>
                                        </div>
                                        <div class="modal-body">
                                            <strong> ¿Está seguro que desea eliminar la cita? </strong>.
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                            <a href="{% url 'agenda:eliminar' i.idCita %}" class="white a_white">
                                              <button type="button" class="btn btn-danger">Eliminar</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                        </div>
                      </td>
                  </tr>
                {%endfor%}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
    <div class="content animate-panel">
      <div class="row">
          <div class="col-lg-12">
              <div class="hpanel hred">
                <div class="panel-heading mayusculas">
                    Sin Citas
                </div>
                <div class="panel-body">
                <table id="clientesTable" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>Cliente</th>
                    <th>Email</th>
                    <th>Cliente Prospecto</th>
                    <th>Opciones</th>
                </tr>
                </thead>
                <tbody>
                {% for i in sin_cita %}
                  <tr>
                      <td>{{i.idCliente.user.first_name}} {{i.idCliente.user.last_name}}</td>
                      <td>{{i.idCliente.user.email}}</td>
                      {% if i.clienteProspecto == True%}
                        <td>Si</td>
                      {% else %}
                        <td>No</td>
                      {% endif %}
                      <td>
                        <a href="{% url 'agenda:agendar' i.idAsesorCliente %}" class="white a_white">
                          <button class="btn btn-warning btn-xs" type="button">
                              <i class="fa fa-pencil"></i>
                          </button>
                        </a>

                      </td>
                  </tr>
                {%endfor%}
              </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <a href="{% url 'login:hola' %}" class="btn btn-success btn-m">
        <span class="bold">Regresar</span>
        <i class="fa fa-angle-right"></i>
    </a>
</div>

  <footer class="footer">
      <span class="pull-right">
          Todos los Derechos Reservados <i class="fa fa-copyright"></i>
      </span>
      Vive Tu Futuro 2017-2020
  </footer>
<!-- Vendor scripts -->
{% endblock %}

templates/agenda/historial.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title%} Mis Clientes {% endblock %}
{% block content %}
<div class="normalheader transition animated fadeIn">
  <div class="hpanel">
      <div class="panel-body">
          <a class="small-header-action" href="">
              <div class="clip-header">
                  <i class="fa fa-arrow-up"></i>
              </div>
          </a>
          <h2 class="font-light m-b-xs">
              Aqui tienes tu historial de citas :).
          </h2>
      </div>
  </div>
  <div class="content">
  <div class="row">
      <div class="col-md-6">
          <div class="hpanel">
            {% for k in historial1  %}
              {% for i in k  %}
                  <div class="v-timeline vertical-container animate-panel" data-child="vertical-timeline-block" data-delay="1">
                      <div class="vertical-timeline-block animated-panel zoomIn" style="animation-delay: 0.2s;">
                          <div class="vertical-timeline-icon navy-bg">
                              <i class="fa fa-calendar"></i>
                          </div>
                          <div class="vertical-timeline-content">
                              <div class="p-sm">
                                  <span class="vertical-date pull-right"> {{i.fecha|date}} <br> <small>{{i.fecha|time}}</small> </span>
                                  <br>
                                    <dl class="dl-horizontal">
                                        <dt>Nombre: </dt>
                                        <dd>{{i.idAsesorCliente.idCliente.user.first_name}}</dd>
                                        <dt>Apellidos: </dt>
                                        <dd>{{i.idAsesorCliente.idCliente.user.last_name}}</dd>
                                        {% if i.direccionCita%}
                                          <dt>Direccion:</dt>
                                          <dd>{{i.direccionCita}}</dd>
                                        {% endif %}
                                        <dt>Fecha y hora:</dt>
                                        <dd>{{i.fecha}}</dd>
                                        <dt>Tipo:</dt>
                                        <dd>{{i.idTipoCita}}</dd>
                                        <dt>Estatus:</dt>
                                        <dd>{{i.idEstatus}}</dd>
                                        <dt>Descripcion</dt>
                                        <dd>{{i.descripcion}}</dd>
                                    </dl>

                              </div>
                              <div class="panel-footer">
                                No olvides contactarlo, sus contactos estan en clientes e informacion.
                              </div>
                          </div>
                      </div>
                  </div>
                {% endfor %}
            {% endfor %}
          </div>
        </div>
        <div class="col-md-6">
            <div class="hpanel">
              {% for k1 in historial2  %}
                {% for j in k1  %}
                    <div class="v-timeline vertical-container animate-panel" data-child="vertical-timeline-block" data-delay="1">
                        <div class="vertical-timeline-block animated-panel zoomIn" style="animation-delay: 0.2s;">
                            <div class="vertical-timeline-icon navy-bg">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <div class="vertical-timeline-content">
                                <div class="p-sm">
                                    <span class="vertical-date pull-right"> {{j.fecha|date}} <br> <small>{{j.fecha|time}}</small> </span>
                                    <br>
                                      <dl class="dl-horizontal">
                                          <dt>Nombre: </dt>
                                          <dd>{{j.idAsesorCliente.idCliente.user.first_name}}</dd>
                                          <dt>Apellidos: </dt>
                                          <dd>{{j.idAsesorCliente.idCliente.user.last_name}}</dd>
                                          {% if i.direccionCita%}
                                            <dt>Direccion:</dt>
                                            <dd>{{i.direccionCita}}</dd>
                                          {% endif %}
                                          <dt>Fecha y hora:</dt>
                                          <dd>{{j.fecha}}</dd>
                                          <dt>Tipo:</dt>
                                          <dd>{{j.idTipoCita}}</dd>
                                          <dt>Estatus:</dt>
                                          <dd>{{j.idEstatus}}</dd>
                                          <dt>Descripcion</dt>
                                          <dd>{{j.descripcion}}</dd>
                                      </dl>
                                </div>
                                <div class="panel-footer">
                                    No olvides contactarlo, sus contactos estan en clientes e informacion.
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
{% endblock %}