asesor/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(
        regex=r'^gestionar/$',
        view=views.gestionarAsesor,
        name='gestionar'
    ),
    url(
        regex=r'^agregar/$',
        view=views.agregarAsesor,
        name='agregar'
    ),
    url(
        regex=r'^ver/(?P<idAsesorPromotor>\d+)$',
        view=views.asesor,
        name='asesor'
    ),
    url(
        regex=r'^eliminar/(?P<idAsesorPromotor>\d+)$',
        view=views.eliminarAsesor,
        name='eliminar'
    ),
    url(
        regex=r'^editar/(?P<idAsesorPromotor>\d+)$',
        view=views.editarAsesor,
        name='editar'
    ),
]

login/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.conf.urls import handler404


urlpatterns = [
    url(r'^logout/$',auth_views.logout,{'template_name':'hola.html'},'logout'),
    url(
        regex=r'^$',
        view=views.login,
        name='login'
    ),
    url(
        regex=r'^hola/$',
        view=views.hola,
        name='hola'
    ),

]

vive/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.principal,name='principal'),
    url(r'^login/',include('login.urls',namespace='login')),
    url(r'^cita/',include('agenda.urls',namespace='agenda')),
    url(r'^asesor/',include('asesor.urls',namespace='asesor')),
    url(r'^ventas/',include('ventas.urls',namespace='ventas')),
    url(r'^sesion1/',include('sesion1.urls',namespace='sesion1')),
    url(r'^cliente/',include('cliente.urls',namespace='cliente')),
    url(r'^creditos/',include('creditos.urls',namespace='conekta')),
    url(r'^mensajes/',include('mensajes.urls',namespace='mensajes')),
    url(r'^productos/',include('productos.urls',namespace='producto')),
    url(r'^reportes/',include('reportes.urls', namespace='reporte')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

asesor/models.py
from django.db import models
from login.models import Persona
from django.contrib.auth.models import User

class ReporteActividad(models.Model):
    idReporte = models.AutoField(primary_key=True)
    idAsesor = models.ForeignKey(User)
    fechaReporte = models.DateField()
    recomendadosObtenidos = models.IntegerField()
    recomendadosContactados = models.IntegerField()
    llamadasRealizadas = models.IntegerField()
    citasObtenidas = models.IntegerField()
    citasTotales = models.IntegerField()
    citasNuevas = models.IntegerField()
    entrevistasInicialesPlaneadas = models.IntegerField()
    entrevistasInicialesRealizadas = models.IntegerField()
    entrevistasCierrePlaneadas = models.IntegerField()
    entrevistasCierreRealizadas = models.IntegerField()
    solicitudesSucritas = models.IntegerField()

asesor/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from promotor.models import promotorAsesor
from django.contrib import auth


class promotorAsesorForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(promotorAsesorForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs = {
                'class': 'form-control'
            }
    class Meta:
        model = promotorAsesor
        fields = (
            'institucion',
        )

asesor/views.py
from django.shortcuts import render,redirect,render_to_response
from django.contrib.auth.decorators import login_required
from . import models as mAsesor
from promotor import models as mPromotor
from login import models as mLogin
from login import forms as fLogin
from cliente import forms as fInfo
from . import forms as f
from django.contrib.auth import get_user
from productos import models as mProductos

# Create your views here.
@login_required(redirect_field_name='login:login')
def agregarAsesor(request):
        if request.user.persona.idRol.idRole == 3:
            if request.method == 'POST':
                usuario = fLogin.UserForm(request.POST)
                persona = fInfo.PersonaForm(request.POST)
                direccion = fInfo.DireccionForm(request.POST)
                contacto = fInfo.ContactoForm(request.POST)
                asesor = f.promotorAsesorForm(request.POST)
                if usuario.is_valid():
                    user = usuario.save()
                    rol = mLogin.Roles.objects.get(idRole=2)
                    fecha = request.POST.get("fechaDeNacimiento",None)
                    estadoCivil = request.POST.get("estadoCivil",None)
                    direccion = request.POST.get("idtipodireccion",None)
                    persona = mLogin.Persona.objects.get(user_id=user)
                    nombreaux = request.POST.get("institucion",None)
                    if estadoCivil == "":
                        estado = mLogin.EstadoCivil.objects.get(idEstadoCivil="1")
                    else:
                        estado = mLogin.EstadoCivil.objects.get(idEstadoCivil=estadoCivil)
                    if direccion == "":
                        tipodireccion = mLogin.CatTipodireccion.objects.get(idtipoDireccion="1")
                    else:
                        tipodireccion = mLogin.CatTipodireccion.objects.get(idtipoDireccion=direccion)
                    if request.POST.get("clienteProspecto",None) == "on":
                        prospecto = True
                    else:
                        prospecto = False

                    nombre = nombreaux.split(" ")
                    print(nombre[0])
                    institucion = mProductos.InstitucionFinanciera.objects.get(idInstitucion=nombre[0])
                    mLogin.Persona.objects.filter(user_id=user).update(
                        estadoCivil = estado,
                        fechaDeNacimiento = fecha,
                        idRol = rol,
                        curp = request.POST.get("curp",None),
                        rfc = request.POST.get("rfc",None),
                    )
                    direccion = mLogin.Direccion(
                        idpersona = persona,
                        idtipodireccion = tipodireccion,
                        calle = request.POST.get("calle",None),
                        colonia = request.POST.get("colonia",None),
                        delegacion = request.POST.get("delegacion",None),
                        cp = request.POST.get("cp",None),
                        numinterior = request.POST.get("numinterior",None),
                        numexterior = request.POST.get("numexterior",None),
                    )
                    contacto = mLogin.Contacto(
                        idpersona = persona,
                        celular = request.POST.get("celular",None),
                        telcasa = request.POST.get("telcasa",None),
                        oficina = request.POST.get("oficina",None),
                        facebookid = request.POST.get("facebookid",None),
                    )
                    promotor = mPromotor.promotorAsesor(
                        idAsesor = persona,
                        idPromotor = get_user(request),
                        institucion = institucion,
                        activo = True,
                    )
                    contacto.save()
                    direccion.save()
                    promotor.save()
                    return redirect('asesor:agregar')
                else:
                    context = {
                        "usuario":usuario,
                        "persona":persona,
                        "contacto":contacto,
                        "direccion":direccion,
                    }
                    return  render_to_response('asesor/asesor_add.html',context)

            usuario = fLogin.UserForm()
            persona = fInfo.PersonaForm()
            direccion = fInfo.DireccionForm()
            contacto = fInfo.ContactoForm()
            asesor = f.promotorAsesorForm()
            context = {
                "usuario":usuario,
                "persona":persona,
                "contacto":contacto,
                "direccion":direccion,
                "asesor":asesor,
            }
            return render(request,"asesor/asesor_add.html",context)


@login_required(redirect_field_name='login:login')
def editarAsesor(request,idAsesorPromotor):
    if request.user.persona.idRol.idRole == 3:
        editar = mPromotor.promotorAsesor.objects.get(idAsesorPromotor=idAsesorPromotor)
        if request.method == 'POST':
            usuario = fLogin.UserForm(request.POST,instance=editar.idAsesor.user)
            persona = fInfo.PersonaForm(request.POST,instance=editar.idAsesor)
            asesor = f.promotorAsesorForm(request.POST,instance=editar)

            if usuario.is_valid():
                print(persona)
                usuario.save()
                persona.save()
                asesor.save()
                return redirect('asesor:gestionarAsesor')
        else:
            usuario = fLogin.UserForm(instance=editar.idAsesor.user)
            persona = fInfo.PersonaForm(instance=editar.idAsesor)
            asesor = f.promotorAsesorForm(instance=editar)
            context = {
                "usuario":usuario,
                "persona":persona,
                "asesor":asesor,
            }
            return render(request,"asesor/asesor_editar.html",context)

    else:
        return render(request,'error/404.html')

@login_required(redirect_field_name='login:login')
def eliminarAsesor(request,idAsesorPromotor):
    if request.user.persona.idRol.idRole == 3:
        eliminar = mPromotor.promotorAsesor.objects.get(idAsesorPromotor=idAsesorPromotor)
        mPromotor.promotorAsesor.objects.filter(idAsesorPromotor=eliminar.idAsesorPromotor).update(
            activo = False
        )
        return redirect('asesor:gestionarAsesor')
    else:
        return render(request,'error/404.html')

@login_required(redirect_field_name='login:login')
def asesor(request,idAsesorPromotor):
    if request.user.persona.idRol.idRole == 3:
        promotorAsesor = mPromotor.promotorAsesor.objects.get(idAsesorPromotor=idAsesorPromotor)
        contacto = mLogin.Contacto.objects.filter(idpersona=promotorAsesor.idAsesor)
        direccion = mLogin.Direccion.objects.filter(idpersona=promotorAsesor.idAsesor)
        context = {
            "asesor":promotorAsesor,
            "contactos":contacto,
            "direcciones":direccion,
        }
        return render(request,"asesor/asesor_show.html",context)
    else:
        return render(request,'error/404.html')


@login_required(redirect_field_name='login:login')
def gestionarAsesor(request):
    if request.user.persona.idRol.idRole == 3:
        promotorAsesor = mPromotor.promotorAsesor.objects.filter(idPromotor=request.user)
        context = {
            "promotorAsesor":promotorAsesor,
        }
        return render(request,"asesor/asesor_gestionar.html",context)
    else:
        return render(request,'error/404.html')

templates/asesor/asesor_add.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title %}Agregar Asesor{% endblock %}

{% block content %}
<!-- Simple splash screen-->
<div class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading mayusculas">
                    Agregar Asesor
                </div>
                <div class="panel-body">
                    <div class="text-center m-b-md" id="wizardControl">
                        <a class="btn btn-primary" href="#step1" data-toggle="tab">Paso 1: Información Personal</a>
                        <a class="btn btn-default" href="#step2" data-toggle="tab">Paso 2: Lugar de trabajo</a>
                        <a class="btn btn-default" href="#step3" data-toggle="tab">Paso 3: Información Geográfica</a>
                        <a class="btn btn-default" href="#step4" data-toggle="tab">Paso 4: Contacto</a>
                    </div>
                      <form method="POST" class="post-form">
                        {% csrf_token %}
                        <div class="tab-content">
                          <div id="step1" class="p-m tab-pane active">
                            <div class="row">
                                <div class="col-lg-3 text-center">
                                    <i class="pe-7s-user fa-5x text-muted"></i>
                                    <p class="small m-t-md">
                                        <strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard.
                                        <br/><br/>Lorem Ipsum has been the industry's dummy text of the printing and typesetting
                                    </p>
                                </div>
                                <div class="col-lg-9">
                                  <div class="alert alert-info">
                                    La contraseña por defecto sera la primera letra del nombre y de los apellidos seguido por c1234.
                                  </div>
                                    <div class="row">
                                        <div class="form-group col-lg-8">
                                            {{usuario.as_p}}
                                            {{persona.as_p}}
                                            {{asesor.as_p}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-right m-t-xs">
                                <a class="btn btn-default next" href="#step2" data-toggle="tab">Siguiente</a>
                            </div>
                        </div>
                        <div id="step2" class="p-m tab-pane">

                        </div>
                        <div id="step3" class="p-m tab-pane">
                            <div class="row">
                                <div class="col-lg-3 text-center">
                                    <i class="pe-7s-map-marker fa-5x text-muted"></i>
                                    <p class="small m-t-md">
                                        <strong>It is a long</strong> established fact that a reader will be distracted by the readable
                                        <br/><br/>Many desktop publishing packages and web page editors now use
                                    </p>
                                </div>
                                <div class="col-lg-9">
                                    <div class="row">
                                        <div class="form-group col-lg-12">
                                            {{direccion.as_p}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-right m-t-xs">
                                <a class="btn btn-default prev" href="#step1" data-toggle="tab">Anterior</a>
                                <a class="btn btn-default next" href="#step3" data-toggle="tab">Siguiente</a>
                            </div>
                        </div>
                          <div id="step4" class="tab-pane">
                              <div class="row">
                                <div class="col-lg-3 text-center">
                                    <i class="pe-7s-call fa-5x text-muted"></i>
                                    <p class="small m-t-md">
                                        <strong>It is a long</strong> established fact that a reader will be distracted by the readable
                                        <br/><br/>Many desktop publishing packages and web page editors now use
                                    </p>
                                </div>
                                <div class="col-lg-9">
                                    <div class="row">
                                        <div class="form-group col-lg-12">
                                          <div class="row">
                                              <div class="col-xs-4 form-group">
                                                <label>{{contacto.celular.label}}:</label>
                                                {{contacto.celular}}
                                              </div>
                                              <div class="col-xs-4 form-group">
                                                <label>{{contacto.telcasa.label}}:</label>
                                                {{contacto.telcasa}}
                                              </div>
                                              <div class="col-xs-4 form-group">
                                                <label>{{contacto.oficina.label}}:</label>
                                                {{contacto.oficina}}
                                              </div>
                                            </div>
                                            <div class="row">
                                              <div class="form-group col-lg-6">
                                                <label>{{contacto.facebookid.label}}:</label>
                                                {{contacto.facebookid}}
                                              </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-right m-t-xs">
                                <a class="btn btn-default prev" href="#step2"data-toggle="tab">Anterior</a>
                                <button class = "btn btn-default" type="submit">Agregar</button>
                            </div>
                        </div>
                      </div>
                    </form>
                    <div class="m-t-md">
                      <p>
                          <strong>Vive Tu Futuro 2017-2020 </strong>  Todos los Derechos Reservados <strong><i class="fa fa-copyright"></i> </strong>
                      </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    <script src="{% static "vendor/toastr/build/toastr.min.js" %}"></script>
{% endblock %}

{% block scripts %}
    <script>
      $(function(){
       //Funcion da estilo a botones
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            $('a[data-toggle="tab"]').removeClass('btn-success');
            $('a[data-toggle="tab"]').addClass('btn-default');
            $(this).removeClass('btn-default');
            $(this).addClass('btn-info');
        });

        function msjRepetido(){
          var bandera = {{bandera}}

          if(bandera == 0){
            toastr.error('Error - Se produjo un error, revisa la caja de errores.');
          }
          else if (bandera == 1){
            toastr.success('Exito - Se agrego correctamente el cliente.');
          }
          else if (bandera == 2){
            toastr.warning('Notificacion - No se pudo mandar el correo, revisar direccion de correo.');
          }
        }
        msjRepetido();
      });
    </script>
{% endblock %}

templates/asesor/asesor_editar.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title %}Agregar Asesor{% endblock %}

{% block content %}
<!-- Simple splash screen-->

<div class="content">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel">
                <div class="panel-heading mayusculas">
                    Editar Asesor
                </div>
                <div class="panel-body">
                      <form method="POST" class="post-form">
                        {% csrf_token %}
                        <div class="tab-content">
                            <div class="row">
                                <div class="col-lg-3 text-center">
                                    <i class="pe-7s-user fa-5x text-muted"></i>
                                    <p class="small m-t-md">
                                        <strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard.
                                        <br/><br/>Lorem Ipsum has been the industry's dummy text of the printing and typesetting
                                    </p>
                                </div>
                                <div class="col-lg-9">
                                    <div class="row">
                                        <div class="form-group col-lg-8">
                                            {{usuario.as_p}}
                                            {{persona.as_p}}
                                            {{asesor.as_p}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="text-right m-t-xs">
                                <button type="submit">Agregar</button>
                            </div>
                      </div>
                    </form>
                    <div class="m-t-md">
                      <p>
                          <strong>Vive Tu Futuro 2017-2020 </strong>  Todos los Derechos Reservados <strong><i class="fa fa-copyright"></i> </strong>
                      </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/asesor/asesor_gestionar.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title %}Mis asesores{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static "vendor/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css" %}">
{% endblock %}
{% block content %}
  <div class="content animate-panel">
      <div class="row">
          <div class="col-lg-12">
              <div class="hpanel hgreen">
                <div class="panel-heading mayusculas">
                    Mis Asesores
                </div>
                <div class="panel-body">
                  <table id="clientesTable" class="table table-striped table-bordered table-hover">
                    <thead>
                      <tr>
                        <th>Asesor</th>
                        <th>Email</th>
                        <th>Institucion</th>
                        <th>Opciones</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for i in promotorAsesor %}
                    {% if i.activo == True %}
                      <tr>
                          <td>{{i.idAsesor.user.first_name}} {{i.idAsesor.user.last_name}}</td>
                          <td>{{i.idAsesor.user.email}}</td>
                          <td>{{i.institucion}}</td>
                          <td>
                              <a href="{% url 'asesor:asesor' i.idAsesorPromotor %}" class="white a_white">
                                <button class="btn btn-info btn-xs" type="button">
                                    <i class="fa fa-info"></i>
                                </button>
                              </a>
                              <a href="{% url 'asesor:editar' i.idAsesorPromotor %}" class="white a_white">
                                <button class="btn btn-warning btn-xs" type="button">
                                    <i class="fa fa-pencil"></i>
                                </button>
                              </a>
                              <button class="btn btn-danger btn-xs" type="button" data-toggle="modal" data-target="#{{i.idAsesorPromotor}}">
                                  <i class="fa fa-times"></i>
                              </button>
                              <div class="modal fade" id="{{i.idAsesorPromotor}}" tabindex="-1" role="dialog" aria-hidden="true">
                                  <div class="modal-dialog">
                                      <div class="modal-content">
                                          <div class="color-line"></div>
                                          <div class="modal-header text-center">
                                              <h4 class="modal-title">Eliminar cliente</h4>
                                          </div>
                                          <div class="modal-body">
                                              Está seguro que desea eliminar al Asesor <strong>{{i.idAsesor.user.first_name}}</strong> todos sus datos personales serán eliminados pero la información sobre ventas permanecerá.
                                          </div>
                                          <div class="modal-footer">
                                              <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                                              <a href="{% url 'asesor:eliminar' i.idAsesorPromotor %}" class="white a_white">
                                                <button type="button" class="btn btn-danger">Eliminar</button>
                                              </a>
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </td>
                      </tr>
                    {% endif %}
                    {%endfor%}
                  </tbody>
                  </table>
                  <a href="{% url 'login:hola' %}" class="btn btn-success btn-m">
                      <span class="bold">Regresar</span>
                      <i class="fa fa-angle-right"></i>
                  </a>
                  <a href="{% url 'asesor:agregar' %}" class="btn btn-success btn-m">
                      <span class="bold">Agregar</span>
                      <i class="icono-der fa fa-plus"></i>
                  </a>
                </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

{% block javascripts %}
    <script src="{% static "vendor/datatables/media/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "vendor/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js" %}"></script>

    <script>

    $(function () {
        $('#clientesTable').dataTable();
    });

  </script>
{% endblock %}

templates/asesor/asesor_show.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block title %}Ver Asesor{% endblock %}
{% block content %}
<!-- Simple splash screen-->

<div class="normalheader transition animated fadeIn">
    <div class="hpanel">
        <div class="panel-body">
            <a class="small-header-action" href="">
                <div class="clip-header">
                    <i class="fa fa-arrow-up"></i>
                </div>
            </a>
            <h3 class="font-light m-b-xs">
                {{user.first_name}} {{user.last_name}}
            </h3>
            <small>Información del cliente.</small>
        </div>
    </div>
</div>
<div class="content animate-panel">
	<div class="row">
		<div class="col-lg-4">
	        <div class="hpanel hblue">
	            <div class="panel-heading hbuilt">
	                <div class="panel-tools">
	                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
	                    <a class="closebox"><i class="fa fa-times"></i></a>
	                </div>
	                Información Personal
	            </div>
	            <div class="panel-body">
               	<dl class="dl-horizontal">
                    <dt>Nombre: </dt>
                    <dd>{{asesor.idAsesor.user.first_name}}</dd>
                    <dt>Apellidos: </dt>
                    <dd>{{asesor.idAsesor.user.last_name}}</dd>
                    <dt>CURP:</dt>
                    <dd>{{asesor.idAsesor.curp}}</dd>
                    <dt>RFC:</dt>
                    <dd>{{asesor.idAsesor.rfc}}</dd>
                    <dt>Fecha de Nacimiento:</dt>
                    <dd>{{asesor.idAsesor.fechaDeNacimiento}}</dd>
                    <dt>Estado Civil</dt>
                    <dd>{{asesor.idAsesor.estadoCivil}}</dd>
                    <dt>Correo Principal</dt>
                    <dd>{{asesor.idAsesor.user.email}}</dd>
                    <dt>Institucion</dt>
                    <dd>{{asesor.institucion}}</dd>
                </dl>
            	</div>
	        </div>
	    </div>
    {% for j in asesor.idAsesor.direccion.all %}
  		<div class="col-lg-4">
  	        <div class="hpanel hyellow">
  	            <div class="panel-heading hbuilt">
  	                <div class="panel-tools">
  	                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
  	                    <a class="closebox"><i class="fa fa-times"></i></a>
  	                </div>
  	                Información Geográfica
  	            </div>
  	            <div class="panel-body">
  	            <h4>Domcilio {{ forloop.counter }} </h4>
  	             <dl class="dl-horizontal">
                      <dt>Tipo de Dirección: </dt>
                      <dd>{{j.idtipodireccion}}</dd>
                      <dt>Delegación / Municipio:</dt>
                      <dd>{{j.delegacion}}</dd>
                      <dt>Calle: </dt>
                      <dd>{{j.calle}}</dd>
                      <dt>Colonia: </dt>
                      <dd>{{j.colonia}}</dd>
                      <dt>Codigo Postal:</dt>
                      <dd>{{j.cp}}</dd>
                  </dl>
              	</div>
  	        </div>
  	    </div>
        {%endfor%}
        {% for j in asesor.idAsesor.contacto.all %}
  	    <div class="col-lg-4">
  	        <div class="hpanel hgreen">
  	            <div class="panel-heading hbuilt">
  	                <div class="panel-tools">
  	                    <a class="showhide"><i class="fa fa-chevron-up"></i></a>
  	                    <a class="closebox"><i class="fa fa-times"></i></a>
  	                </div>
  	                Contacto
  	            </div>
                <div class="panel-body">
                <h4>Contacto {{ forloop.counter }} </h4>
  	             <dl class="dl-horizontal">
                      <dt>Celular: </dt>
                      <dd>{{j.celular}}</dd>
                      <dt>Casa:</dt>
                      <dd>{{j.telcasa}}</dd>
                      <dt>Oficina: </dt>
                      <dd>{{j.oficina}}</dd>
                      <dt>Correo Secundario:</dt>
                      <dd>{{j.email}}</dd>
                      <dt>Facebook:</dt>
                      <dd>{{j.facebookid}}</dd>
                  </dl>
              	</div>
  	        </div>
  	    </div>
        {%endfor%}
  	</div>
</div>
    <!-- Footer-->

</div>

{% endblock %}