agenda/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
urlpatterns = [
    url(
        regex=r'^contactos',
        view=views.contactos,
        name='contactos'
    ),
    url(
        regex=r'^$',
        view=views.calendario,
        name='calendario'
    ),
    url(
        regex=r'^agendar/(?P<idAsesorCliente>\d+)$',
        view=views.agenda,
        name='agendar'
    ),
    url(
        regex=r'^editar/(?P<idCita>\d+)$',
        view=views.editar,
        name='editar'
    ),
    url(
        regex=r'^eliminar/(?P<idCita>\d+)$',
        view=views.eliminar,
        name='eliminar'
    ),
    url(
        regex=r'^hoy/',
        view=views.hoy,
        name='hoy'
    ),
    url(
        regex=r'^historial/',
        view=views.historial,
        name='historial'
    ),
]

asesor/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(
        regex=r'^gestionar/$',
        view=views.gestionarAsesor,
        name='gestionar'
    ),
    url(
        regex=r'^agregar/$',
        view=views.agregarAsesor,
        name='agregar'
    ),
    url(
        regex=r'^ver/(?P<idAsesorPromotor>\d+)$',
        view=views.asesor,
        name='asesor'
    ),
    url(
        regex=r'^eliminar/(?P<idAsesorPromotor>\d+)$',
        view=views.eliminarAsesor,
        name='eliminar'
    ),
    url(
        regex=r'^editar/(?P<idAsesorPromotor>\d+)$',
        view=views.editarAsesor,
        name='editar'
    ),
]

cliente/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(
        regex=r'^registrar/$',
        view=views.agregarCliente,
        name='agregarCliente'
    ),
    url(
        regex=r'^(?P<idAsesorCliente>\d+)$',
        view=views.clientes,
        name='clientes'
    ),
    url(
        regex=r'^gestionar/$',
        view=views.gestionarClientes,
        name='gestionarCliente'
    ),
    url(
        regex=r'^editar/(?P<idAsesorCliente>\d+)$',
        view=views.editar,
        name='editar'
    ),
    url(
        regex=r'^eliminar/(?P<idAsesorCliente>\d+)$',
        view=views.eliminar,
        name='eliminar'
    ),
    url(
        regex=r'^hola/$',
        view=views.hola,
        name='hola'
    ),
    url(
        regex=r'^recomendar/$',
        view=views.recomendar,
        name='recomendar'
    ),
    url(
        regex=r'^recomendados/$',
        view=views.recomendados,
        name='recomendados'
    ),
]

creditos/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        regex=r'^orden/$',
        view=views.orden,
        name='orden'
    ),
	url(
		regex=r'^inicio/$',
		view=views.index,
		name='inicio'
	),
]

vive/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.principal,name='principal'),
    url(r'^login/',include('login.urls',namespace='login')),
    url(r'^cita/',include('agenda.urls',namespace='agenda')),
    url(r'^asesor/',include('asesor.urls',namespace='asesor')),
    url(r'^ventas/',include('ventas.urls',namespace='ventas')),
    url(r'^sesion1/',include('sesion1.urls',namespace='sesion1')),
    url(r'^cliente/',include('cliente.urls',namespace='cliente')),
    url(r'^creditos/',include('creditos.urls',namespace='conekta')),
    url(r'^mensajes/',include('mensajes.urls',namespace='mensajes')),
    url(r'^productos/',include('productos.urls',namespace='producto')),
    url(r'^reportes/',include('reportes.urls', namespace='reporte')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/perfil/dashboard.html
{% extends 'base/vistas_base.html' %}
{% load static  %}
{% block content %}

	<div class="dashboard">
		<div class="content animate-panel">
			<!--Main row-->
			<div class="row">
				<!--Normal Sections-->
				<div class="col-md-6">
					<div class="row">
							<div class="col-md-6">
									<div class="hpanel">
											<div class="panel-body">
													<div class="stats-title pull-left">
															<h4>Clientes</h4>
													</div>
													<div class="stats-icon pull-right">
															<i class="pe-7s-user  fa-4x"></i>
													</div>
													<div class="m-t-xl">
															<h1 class="text-success">{{clientes}}</h1>
															<small>
																	Lorem Ipsum is simply dummy text of the printing and <strong>typesetting industry</strong>. Lorem Ipsum has been.
															</small>
													</div>
													<div class="m-t-xl text-center">
															<a href="{% url 'cliente:agregarCliente' %}" class="btn btn-success btn-m">
																<span class="bold">Agregar</span>
																<i class="fa fa-pencil"></i>
															</a>
															<a href="{% url 'cliente:gestionarCliente' %}" class="btn btn-success btn-m">
																	<span class="bold">Ver más</span>
																	<i class="fa fa-angle-right"></i>
															</a>
											</div>
											</div>
									</div>
							</div>
							<div class="col-md-6">
									<div class="hpanel">
											<div class="panel-body">
													<div class="stats-title pull-left">
															<h4>Ventas</h4>
													</div>
													<div class="stats-icon pull-right">
															<i class="pe-7s-cash fa-4x"></i>
													</div>
													<div class="m-t-xl">
															<h1 class="text-info">$50,000</h1>
															<small>
																	Lorem Ipsum is simply dummy text of the printing and <strong>typesetting industry</strong>. Lorem Ipsum has been.
															</small>
													</div>
													<div class="m-t-xl text-center">
														<button class="btn btn-info	 btn-m">
															<span class="bold">Ver más</span>
															<i class="fa fa-angle-right"></i>
													</button>
											</div>
											</div>
									</div>
							</div>
						</div> <!--row 2-->
						<div class="row">
							<div class="col-md-6">
									<div class="hpanel">
											<div class="panel-body">
													<div class="stats-title pull-left">
															<h4>Creditos</h4>
													</div>
													<div class="stats-icon pull-right">
															<i class="pe-7s-ticket fa-4x"></i>
													</div>
													<div class="m-t-xl">
															<h1 class="text-warning">{{creditos}}</h1>
															<small>
																	Lorem Ipsum is simply dummy text of the printing and <strong>typesetting industry</strong>. Lorem Ipsum has been.
															</small>
													</div>
													<div class="m-t-xl text-center">
														<a href="{% url 'conekta:orden' %}" class="btn btn-warning	 btn-m">
															 <span class="bold">Comprar</span>
															 <i class="fa fa-usd"></i>
														</a>
														<a href="{% url 'conekta:inicio' %}" class="btn btn-warning	 btn-m">
															 <span class="bold">Ver más</span>
															 <i class="fa fa-angle-right"></i>
														</a>
													</div>
											</div>
									</div>
							</div>
							<div class="col-md-6">
									<div class="hpanel">
											<div class="panel-body">
													<div class="stats-title pull-left">
															<h4>Citas</h4>
													</div>
													<div class="stats-icon pull-right">
															<i class="pe-7s-bookmarks fa-4x"></i>
													</div>
													<div class="m-t-xl">
															<h1 class="text-danger">{{citas}}</h1>
															<small>
																	Lorem Ipsum is simply dummy text of the printing and <strong>typesetting industry</strong>. Lorem Ipsum has been.
															</small>
													</div>
													<div class="m-t-xl text-center">
														<a href="{% url 'agenda:calendario' %}" class="btn btn-danger	 btn-m">
															<span class="bold">Ver más</span>
															<i class="fa fa-angle-right"></i>
														</a>
											</div>
											</div>
									</div>
							</div>
						</div><!--row-->
						<div class="row">
							<div class="col-md-6">
											<div class="hpanel">
													<div class="panel-body">
															<div class="stats-title pull-left">
																	<h4>Productos</h4>
															</div>
															<div class="stats-icon pull-right">
																	<i class="pe-7s-box1 fa-4x"></i>
															</div>
															<div class="m-t-xl">
																	<h1 class="text-primary">6</h1>
																	<small>
																			Lorem Ipsum is simply dummy text of the printing and <strong>typesetting industry</strong>. Lorem Ipsum has been.
																	</small>
															</div>
															<div class="m-t-xl text-center">
																<div class="btn-group dropup">
																		<button data-toggle="dropdown" class="btn btn-primary dropdown-toggle">Agregar <span class="caret"></span></button>
																		<ul class="dropdown-menu dropup">
																				<li><a href="{% url 'producto:agregarProducto' %}">Producto</a></li>
																				<li><a href="{% url 'producto:agregarProducto' %}">Departamentos</a></li>
																				<li><a href="{% url 'producto:agregarProducto' %}">Institucion Financiera</a></li>
																		</ul>
																</div>
																<div class="btn-group dropup">
																		<button data-toggle="dropdown" class="btn btn-primary dropdown-toggle">Ver más <span class="caret"></span></button>
																		<ul class="dropdown-menu dropup">
																				<li><a href="{% url 'producto:gestionarProducto' %}">Producto</a></li>
																				<li><a href="{% url 'producto:gestionarProducto' %}">Departamentos</a></li>
																				<li><a href="{% url 'producto:gestionarProducto' %}">Institucion Financiera</a></li>
																		</ul>
																</div>
															</div>
													</div>
											</div>
								</div>
								{%if rol == 3 %}
							<div class="col-md-6">
								 <div class="hpanel">
										 <div class="panel-body">
												 <div class="stats-title pull-left">
														 <h4>Asesores</h4>
												 </div>
												 <div class="stats-icon pull-right">
														 <i class="pe-7s-user  fa-4x"></i>
												 </div>
												 <div class="m-t-xl">
														 <h1 class="text-success">{{asesores}}</h1>
														 <small>
																 Lorem Ipsum is simply dummy text of the printing and <strong>typesetting industry</strong>. Lorem Ipsum has been.
														 </small>
												 </div>
												 <div class="m-t-xl text-center">
													 <a href="{% url 'asesor:agregar' %}" class="btn btn-success btn-m">
															<span class="bold">Agregar</span>
														 <i class="fa fa-pencil"></i>
														</a>
													 <a href="{% url 'asesor:gestionar' %}" class="btn btn-success btn-m">
																<span class="bold">Ver más</span>
															 <i class="fa fa-angle-right"></i>
														</a>
										 </div>
										 </div>
								 </div>
						 </div>
						 	{% endif %}
						</div><!--row-->
				</div><!--col-md-6-->
				<div class="col-md-6">
					<div class="row">
						<div class="col-md-6">
										<div class="hpanel hbgblue">
												<div class="panel-body">
														<div class="text-center">
														<h3><i class="fa-file-pdf-o fa white"></i>  Reportes</h3>
																<div class="m-t-xl">
																<p>
																		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
																</p>
														</div>
														<div class="m-t-xl">
															<a href="{% url 'reportes:reportes' %}" class="btn btn-default btn-m">
																	<span class="bold">Ver más</span>
																 <i class="fa fa-angle-right"></i>
															</a>
														</div>
														<br>
														</div>
												</div>
										</div>
								</div>
								<div class="col-md-6">
												<div class="hpanel hbgred">
														<div class="panel-body">
																<div class="text-center">
																		<h3><i class="fa-exclamation-circle fa white"></i> Evento</h3>
																		<div class="m-t-xl">
																		<p>
																			{% if hoy == 0 %}
																				El día de hoy no tienes citas, consigue mas :) o disfruta a tu familia <strong> ¡Eres el mejor!	</strong>
																			{% else %}
																				El día de hoy tienes <strong> {{hoy}} </strong> citas, son muy importantes <strong> eres el mejor	</strong>, ¡Éxito!
																			{% endif %}
																		</p>
																</div>
																	{% if hoy == 0 %}
																	<div class="m-t-xl">
																			<a href="{% url 'agenda:contactos' %}" class="btn btn-default btn-m">
																					<span class="bold">Haz mas citas</span>
																				 <i class="fa fa-angle-right"></i>
																			</a>
																	</div>
																	{% else %}
																	<div class="m-t-xl">
																			<a href="{% url 'agenda:hoy' %}" class="btn btn-default btn-m">
																					<span class="bold">Ver mis citas</span>
																				 <i class="fa fa-angle-right"></i>
																			</a>
																	</div>
																	{% endif %}

															<br>
																</div>
														</div>
												</div>
										</div>
							<div class="col-md-12">
										<div class="hpanel">
												<div class="panel-body list">
														<div class="table-responsive project-list">
																<table class="table table-striped">
																		<thead>
																		<tr>
																				<th>Clientes recomendados</th>
																				<th>Nombre</th>
																				<th>celular</th>
																		</tr>
																		</thead>
																		<tbody>
																			{% for i in recomendados  %}
																				<tr>
																						<td>
																								<small><i class="fa fa-clock-o"></i>{{forloop.counter}}</small>
																						</td>
																						<td>{{i.nombre}}</td>
																						<td>{{i.celular}}</td>
																			{% endfor %}
																		</tbody>
																</table>
														</div>
														<a href="{% url 'cliente:recomendados' %}" class="btn btn-default btn-m">
																<span class="bold">Ver mas</span>
															 <i class="fa fa-angle-right"></i>
														</a>
												</div>
										</div>
								</div>
							<div class="col-md-12">
										<div class="hpanel">
												<div class="panel-body list">
														<div class="table-responsive project-list">
																<table class="table table-striped">
																		<thead>
																		<tr>
																				<th>Eventos de la semana</th>
																				<th>Cliente</th>
																				<th>Tipo</th>
																				<th>Direccion</th>
																				<th>Estatus</th>
																		</tr>
																		</thead>
																		<tbody>
																			{% for i in pendientes  %}
																				<tr>
																						<td>
																								<small><i class="fa fa-clock-o"></i>{{i.fecha}}</small>
																						</td>
																						<td>
																								<span class="pie">{{i.idAsesorCliente.idCliente.user.first_name}} {{i.idAsesorCliente.idCliente.user.last_name}}</span>
																						</td>
																						<td>
																								<span class="pie">{{i.idTipoCita.nombre}}</span>
																						</td>
																						<td>{{i.direccionCita}}</td>
																						<td>{{i.idEstatus.nombre}}</td>
																			{% endfor %}
																		</tbody>
																</table>
														</div>
												</div>
										</div>
								</div>
						</div>
				</div>
			</div> <!--Main row-->
		</div> <!--Content animated-->
	</div><!--Dashboard-->

	<!-- Vendor scripts -->
<!-- Vendor scripts -->
{% endblock %}